### ISSUE TITLE
exception handler seems broken

### ISSUE THREAD

**Issue by op7ic** [dionach/HeadersAnalyzer#3]
Hello, 

I get the following error when loading this extension: 

SyntaxError: ("mismatched input 'as' expecting COLON", ('\bapps\8b4fe2571ec54983b6d6c21fbfe17cb2\HeadersAnalyzer.py', 350, 27, '            except IOError as e:\n'))

```
at org.python.core.ParserFacade.fixParseError(ParserFacade.java:92)
at org.python.core.ParserFacade.parse(ParserFacade.java:184)
at org.python.core.Py.compile_flags(Py.java:1731)
at org.python.core.__builtin__.execfile_flags(__builtin__.java:514)
at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at burp.tt.<init>(Unknown Source)
at burp.pxf.a(Unknown Source)
at burp.wke.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)


at org.python.core.ParserFacade.fixParseError(ParserFacade.java:92)
at org.python.core.ParserFacade.parse(ParserFacade.java:184)
at org.python.core.Py.compile_flags(Py.java:1731)
at org.python.core.__builtin__.execfile_flags(__builtin__.java:514)
at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at burp.tt.<init>(Unknown Source)
at burp.pxf.a(Unknown Source)
at burp.wke.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
```

Java: 8.77
Env: Win 8.1

**Comment by ghost** [comment]
Hi,

That is strange, I've checked that line, and it does have the colon:

[...]
except IOError as e:
[...]

What version of Jython do you have? Jython 2.7+ is needed.

**Comment by op7ic** [comment]
yup 2.7 used

**Comment by ghost** [comment]
Could you download the extension and install it manually instead of through the Burp "market"?, you have all the details here: https://github.com/Dionach/HeadersAnalyzer

**Comment by op7ic** [comment]
will do thx
